"use client";

import { useState, useEffect } from "react";
import { ComparisonImportSchema } from "@/shared/types/models";
import { createComparisonDirect } from "@/actions/admin-comparisons";
import { ComparisonForm } from "@/components/admin/ComparisonForm";
import { CreatePageTabs } from "@/components/admin/CreatePageTabs";
import { JsonImportTab } from "@/components/admin/JsonImportTab";
import { useRouter } from "next/navigation";
import { Loader2 } from "lucide-react";

interface AreaOption {
  _id: string;
  name: string;
  slug: string;
}

const exampleJson = JSON.stringify({
  area1: "AREA_1_OBJECT_ID",
  area2: "AREA_2_OBJECT_ID",
  isAutoGenerated: false,
  isActive: true,
  sortOrder: 0,
  heroHeading: "Vijay Nagar vs Super Corridor: Which Area to Buy in Indore?",
  metaTitle: "Vijay Nagar vs Super Corridor Property Comparison",
  metaDescription: "Compare Vijay Nagar and Super Corridor — pricing, connectivity, and investment potential.",
  introText: "Two of Indore's most sought-after localities...",
  verdict: "Super Corridor is better for long-term investment",
  verdictForBudgets: [
    { budgetLabel: "Under ₹50L", recommendedArea: "area2", reason: "More affordable options" }
  ],
  keyDifferences: [
    { parameter: "Avg Price/sqft", area1Value: "₹4,500", area2Value: "₹3,800" }
  ],
  whoBuysHere: {
    area1Profile: "Middle-class families, govt employees",
    area2Profile: "IT professionals, investors"
  }
}, null, 2);

export default function CreateComparisonPage() {
  const router = useRouter();
  const [areas, setAreas] = useState<AreaOption[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/areas")
      .then((r) => r.json())
      .then((data) => {
        if (Array.isArray(data)) setAreas(data);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[50vh]">
        <Loader2 size={24} className="animate-spin text-slate-400" />
      </div>
    );
  }

  const isSchema = ComparisonImportSchema as unknown as {
    safeParse: (data: unknown) => { success: boolean; error?: { flatten: () => { fieldErrors: Record<string, string[]> }; message?: string }; data?: unknown };
  };

  return (
    <CreatePageTabs
      formEntry={<ComparisonForm areas={areas} />}
      jsonImport={
        <JsonImportTab
          schema={isSchema}
          action={createComparisonDirect}
          label="Comparison"
          exampleJson={exampleJson}
          onSuccess={() => router.push("/admin/comparisons")}
        />
      }
    />
  );
}
