"use server";

import { revalidatePath } from "next/cache";
import { connectForWrites } from "@/infrastructure/db/connection";
import { getAdminSession } from "@/lib/auth-guard";
import { AreaModel } from "@/features/colony-intelligence/models/Area";
import { AreaComparisonModel } from "@/features/comparisons/models/AreaComparison";
import { slugify } from "@/utils/slug";
import { ComparisonImportSchema } from "@/shared/types/models";

const comparisonSchema = ComparisonImportSchema;

async function assertAdmin() {
  const s = await getAdminSession();
  if (!s?.user?.email || s.user.role !== "admin") {
    return false;
  }
  return true;
}

function parseComparisonFormData(formData: FormData) {
  const raw = Object.fromEntries(formData.entries());

  let whoBuysHere: { area1Profile: string; area2Profile: string } | undefined;
  try {
    const wbh = formData.get("whoBuysHere");
    if (wbh) whoBuysHere = JSON.parse(String(wbh));
  } catch { /* ignore */ }

  const verdictForBudgets: { budgetLabel: string; recommendedArea: "area1" | "area2"; reason: string }[] = [];
  const budgetKeys = Array.from(formData.keys()).filter((k) => k.startsWith("verdictForBudgets["));
  const budgetIndices = new Set(budgetKeys.map((k) => Number(k.match(/\[(\d+)\]/)?.[1])).filter((n) => !isNaN(n)));
  for (const i of budgetIndices) {
    const budgetLabel = formData.get(`verdictForBudgets[${i}][budgetLabel]`)?.toString() || "";
    const recommendedArea = formData.get(`verdictForBudgets[${i}][recommendedArea]`)?.toString() as "area1" | "area2" | undefined;
    const reason = formData.get(`verdictForBudgets[${i}][reason]`)?.toString() || "";
    if (budgetLabel && recommendedArea) {
      verdictForBudgets.push({ budgetLabel, recommendedArea, reason });
    }
  }

  const keyDifferences: { parameter: string; area1Value: string; area2Value: string }[] = [];
  const diffKeys = Array.from(formData.keys()).filter((k) => k.startsWith("keyDifferences["));
  const diffIndices = new Set(diffKeys.map((k) => Number(k.match(/\[(\d+)\]/)?.[1])).filter((n) => !isNaN(n)));
  for (const i of diffIndices) {
    const parameter = formData.get(`keyDifferences[${i}][parameter]`)?.toString() || "";
    const area1Value = formData.get(`keyDifferences[${i}][area1Value]`)?.toString() || "";
    const area2Value = formData.get(`keyDifferences[${i}][area2Value]`)?.toString() || "";
    if (parameter) {
      keyDifferences.push({ parameter, area1Value, area2Value });
    }
  }

  return { raw, whoBuysHere, verdictForBudgets, keyDifferences };
}

export async function createComparison(
  _prev: unknown,
  formData: FormData
) {
  if (!(await assertAdmin())) return { ok: false as const, error: "Unauthorized" };

  const { raw, whoBuysHere, verdictForBudgets, keyDifferences } = parseComparisonFormData(formData);

  const parsed = comparisonSchema.safeParse({
    area1: raw.area1,
    area2: raw.area2,
    isAutoGenerated: raw.isAutoGenerated === "true",
    isActive: raw.isActive === "true" || raw.isActive === "on",
    sortOrder: raw.sortOrder || 0,
    metaTitle: raw.metaTitle || undefined,
    metaDescription: raw.metaDescription || undefined,
    heroHeading: raw.heroHeading || undefined,
    introText: raw.introText || undefined,
    verdict: raw.verdict || undefined,
    verdictForBudgets,
    keyDifferences,
    whoBuysHere
  });

  if (!parsed.success) return { ok: false as const, error: parsed.error.flatten().fieldErrors };

  if (parsed.data.area1 === parsed.data.area2) {
    return { ok: false as const, error: "Cannot compare an area with itself" };
  }

  try {
    await connectForWrites();

    const [area1, area2] = await Promise.all([
      AreaModel.findById(parsed.data.area1).select("name slug").lean().exec(),
      AreaModel.findById(parsed.data.area2).select("name slug").lean().exec()
    ]);

    if (!area1 || !area2) {
      return { ok: false as const, error: "One or both areas not found" };
    }

    const slug = slugify(`${area1.slug}-vs-${area2.slug}`);

    const heroHeading =
      raw.heroHeading?.toString().trim() ||
      `${area1.name} vs ${area2.name}: Which Area to Buy in Indore?`;

    const metaTitle =
      raw.metaTitle?.toString().trim() ||
      `${area1.name} vs ${area2.name} Property Comparison | AreaMatch`;

    const metaDescription =
      raw.metaDescription?.toString().trim() ||
      `Compare ${area1.name} and ${area2.name} — pricing, connectivity, schools, hospitals, and investment potential. Find the best area for your budget in Indore.`;

    await AreaComparisonModel.create({
      slug,
      area1: parsed.data.area1,
      area2: parsed.data.area2,
      isAutoGenerated: parsed.data.isAutoGenerated,
      isActive: parsed.data.isActive,
      sortOrder: parsed.data.sortOrder,
      heroHeading,
      metaTitle,
      metaDescription,
      introText: raw.introText?.toString().trim() || undefined,
      verdict: raw.verdict?.toString().trim() || undefined,
      verdictForBudgets: parsed.data.verdictForBudgets,
      keyDifferences: parsed.data.keyDifferences,
      whoBuysHere: parsed.data.whoBuysHere
    });

    revalidatePath("/comparisons");
    revalidatePath("/admin/comparisons");
    return { ok: true as const };
  } catch (e) {
    return { ok: false as const, error: String(e) };
  }
}

export async function createComparisonDirect(data: Record<string, unknown>) {
  if (!(await assertAdmin())) return { ok: false as const, error: "Unauthorized" };

  const parsed = comparisonSchema.safeParse(data);
  if (!parsed.success) return { ok: false as const, error: parsed.error.flatten().fieldErrors };

  if (parsed.data.area1 === parsed.data.area2) {
    return { ok: false as const, error: "Cannot compare an area with itself" };
  }

  try {
    await connectForWrites();

    const [area1, area2] = await Promise.all([
      AreaModel.findById(parsed.data.area1).select("name slug").lean().exec(),
      AreaModel.findById(parsed.data.area2).select("name slug").lean().exec()
    ]);

    if (!area1 || !area2) {
      return { ok: false as const, error: "One or both areas not found" };
    }

    const slug = slugify(`${area1.slug}-vs-${area2.slug}`);

    await AreaComparisonModel.create({
      slug,
      ...parsed.data,
      heroHeading: parsed.data.heroHeading || `${area1.name} vs ${area2.name}: Which Area to Buy in Indore?`,
      metaTitle: parsed.data.metaTitle || `${area1.name} vs ${area2.name} Property Comparison | AreaMatch`,
      metaDescription: parsed.data.metaDescription || `Compare ${area1.name} and ${area2.name} — pricing, connectivity, schools, hospitals, and investment potential. Find the best area for your budget in Indore.`
    });

    revalidatePath("/comparisons");
    revalidatePath("/admin/comparisons");
    return { ok: true as const };
  } catch (e) {
    return { ok: false as const, error: String(e) };
  }
}

export async function updateComparison(
  id: string,
  _prev: unknown,
  formData: FormData
) {
  if (!(await assertAdmin())) return { ok: false as const, error: "Unauthorized" };

  const raw = Object.fromEntries(formData.entries());

  const parsed = comparisonSchema.safeParse({
    area1: raw.area1,
    area2: raw.area2,
    isActive: raw.isActive === "true" || raw.isActive === "on",
    sortOrder: raw.sortOrder || 0,
    metaTitle: raw.metaTitle || undefined,
    metaDescription: raw.metaDescription || undefined,
    heroHeading: raw.heroHeading || undefined,
    introText: raw.introText || undefined,
    verdict: raw.verdict || undefined
  });

  if (!parsed.success) return { ok: false as const, error: parsed.error.flatten().fieldErrors };

  try {
    await connectForWrites();

    const update: Record<string, unknown> = {
      isActive: parsed.data.isActive,
      sortOrder: parsed.data.sortOrder
    };

    if (raw.metaTitle?.toString().trim()) update.metaTitle = raw.metaTitle.toString().trim();
    if (raw.metaDescription?.toString().trim()) update.metaDescription = raw.metaDescription.toString().trim();
    if (raw.heroHeading?.toString().trim()) update.heroHeading = raw.heroHeading.toString().trim();
    if (raw.introText?.toString().trim()) update.introText = raw.introText.toString().trim();
    if (raw.verdict?.toString().trim()) update.verdict = raw.verdict.toString().trim();

    await AreaComparisonModel.findByIdAndUpdate(id, { $set: update }).exec();

    revalidatePath("/comparisons");
    revalidatePath(`/comparisons/${raw.slug || id}`);
    revalidatePath("/admin/comparisons");
    return { ok: true as const };
  } catch (e) {
    return { ok: false as const, error: String(e) };
  }
}

export async function deleteComparison(id: string) {
  if (!(await assertAdmin())) return { ok: false as const, error: "Unauthorized" };
  await connectForWrites();
  await AreaComparisonModel.findByIdAndDelete(id).exec();
  revalidatePath("/comparisons");
  revalidatePath("/admin/comparisons");
  return { ok: true as const };
}

export async function getComparisons() {
  if (!(await assertAdmin())) return [];
  await connectForWrites();
  const docs = await AreaComparisonModel.find({})
    .populate("area1", "name slug")
    .populate("area2", "name slug")
    .sort({ sortOrder: 1 })
    .lean()
    .exec();
  return docs;
}

export async function getComparisonById(id: string) {
  if (!(await assertAdmin())) return null;
  await connectForWrites();
  const doc = await AreaComparisonModel.findById(id).lean().exec();
  return doc ?? null;
}

export async function autoGenerateComparisons(areaIds: string[]) {
  if (!(await assertAdmin())) return { ok: false as const, error: "Unauthorized" };

  await connectForWrites();
  let created = 0;
  let skipped = 0;
  const errors: string[] = [];

  const areas = await AreaModel.find({ _id: { $in: areaIds } })
    .select("name slug")
    .lean()
    .exec();

  const areaMap = new Map(areas.map((a) => [String(a._id), { name: a.name, slug: a.slug }]));

  for (let i = 0; i < areaIds.length; i++) {
    for (let j = i + 1; j < areaIds.length; j++) {
      const id1 = areaIds[i];
      const id2 = areaIds[j];

      try {
        const existing = await AreaComparisonModel.findOne({
          $or: [
            { area1: id1, area2: id2 },
            { area1: id2, area2: id1 }
          ]
        }).lean().exec();

        if (existing) {
          skipped++;
          continue;
        }

        const a1 = areaMap.get(id1);
        const a2 = areaMap.get(id2);

        if (!a1 || !a2) {
          errors.push(`Area not found for one of: ${id1}, ${id2}`);
          continue;
        }

        const slug = slugify(`${a1.slug}-vs-${a2.slug}`);

        await AreaComparisonModel.create({
          slug,
          area1: id1,
          area2: id2,
          isAutoGenerated: true,
          isActive: true,
          sortOrder: 0,
          heroHeading: `${a1.name} vs ${a2.name}: Which Area to Buy in Indore?`,
          metaTitle: `${a1.name} vs ${a2.name} Property Comparison | AreaMatch`,
          metaDescription: `Compare ${a1.name} and ${a2.name} — pricing, connectivity, schools, hospitals, and investment potential. Find the best area for your budget in Indore.`
        });

        created++;
      } catch (e) {
        errors.push(`Failed for pair (${id1}, ${id2}): ${String(e)}`);
      }
    }
  }

  revalidatePath("/admin/comparisons");
  return { ok: true as const, created, skipped, errors };
}
