import mongoose, { Schema } from "mongoose";

const { model, models } = mongoose;

const AreaComparisonSchema = new Schema(
  {
    slug: {
      type: String,
      required: true,
      unique: true,
      index: true,
      lowercase: true
    },

    area1: {
      type: Schema.Types.ObjectId,
      ref: "Area",
      required: true
    },

    area2: {
      type: Schema.Types.ObjectId,
      ref: "Area",
      required: true
    },

    isAutoGenerated: {
      type: Boolean,
      default: false
    },

    isActive: {
      type: Boolean,
      default: true
    },

    sortOrder: {
      type: Number,
      default: 0
    },

    // SEO
    metaTitle: String,
    metaDescription: String,
    heroHeading: String,
    introText: String,

    // Editorial
    verdict: String,

    verdictForBudgets: [
      {
        budgetLabel: { type: String, required: true },
        recommendedArea: {
          type: String,
          enum: ["area1", "area2"],
          required: true
        },
        reason: { type: String, required: true }
      }
    ],

    keyDifferences: [
      {
        parameter: { type: String, required: true },
        area1Value: { type: String, required: true },
        area2Value: { type: String, required: true }
      }
    ],

    whoBuysHere: {
      area1Profile: { type: String, default: "" },
      area2Profile: { type: String, default: "" }
    }
  },
  {
    timestamps: true
  }
);

export const AreaComparisonModel =
  models.AreaComparison || model("AreaComparison", AreaComparisonSchema);
