"use client";

import React, { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { AdminDataTable } from "@/components/admin/DataTable";
import { AutoGenerateModal } from "@/components/admin/AutoGenerateModal";
import { deleteComparison } from "@/actions/admin-comparisons";
import { Sparkles } from "lucide-react";

interface ComparisonItem {
  _id: string;
  slug: string;
  isAutoGenerated?: boolean;
  isActive?: boolean;
  area1?: { name: string; slug: string } | null;
  area2?: { name: string; slug: string } | null;
}

export function ComparisonListClient({ comparisons }: { comparisons: ComparisonItem[] }) {
  const router = useRouter();
  const [pending, start] = useTransition();
  const [showAutoGen, setShowAutoGen] = useState(false);

  const columns = [
    {
      header: "Areas",
      accessor: (item: ComparisonItem) => {
        const a1 = item.area1 as { name: string } | null;
        const a2 = item.area2 as { name: string } | null;
        return (
          <span className="font-medium text-slate-800">
            {a1?.name ?? "?"} vs {a2?.name ?? "?"}
          </span>
        );
      },
    },
    {
      header: "Slug",
      accessor: "slug" as keyof ComparisonItem,
    },
    {
      header: "Auto",
      accessor: (item: ComparisonItem) =>
        item.isAutoGenerated ? (
          <span className="inline-flex rounded-full bg-purple-100 px-2 py-0.5 text-xs font-semibold text-purple-700">
            Auto
          </span>
        ) : null,
    },
    {
      header: "Status",
      accessor: (item: ComparisonItem) =>
        item.isActive ? (
          <span className="inline-flex rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-semibold text-emerald-700">
            Active
          </span>
        ) : (
          <span className="inline-flex rounded-full bg-slate-100 px-2 py-0.5 text-xs font-semibold text-slate-500">
            Inactive
          </span>
        ),
    },
  ];

  const handleDelete = (item: ComparisonItem) => {
    if (!confirm("Delete this comparison?")) return;
    start(async () => {
      await deleteComparison(item._id);
      router.refresh();
    });
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <button
          type="button"
          onClick={() => setShowAutoGen((v) => !v)}
          className="flex items-center gap-2 rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 transition-colors hover:bg-slate-50"
        >
          <Sparkles size={16} className="text-purple-500" />
          {showAutoGen ? "Close Auto-Generate" : "Auto-Generate"}
        </button>
      </div>

      {showAutoGen && <AutoGenerateModal onDone={() => { setShowAutoGen(false); router.refresh(); }} />}

      <AdminDataTable
        title="Comparisons"
        data={comparisons}
        columns={columns}
        createLink="/admin/comparisons/create"
        onEdit={(item) => router.push(`/admin/comparisons/${item._id}/edit`)}
        onDelete={handleDelete}
      />
    </div>
  );
}
